### ISSUE TITLE
Regression in 37fe672

### ISSUE THREAD

**Issue by dodomorandi** [lu-zero/tree-sitter-core#16]
When I rebased to master in #13 I had some failing tests. I discovered that the regression is in commit 37fe672.

I think that we should revert the part of the commit that involved rust files, in order to keep the integration with the CI without regressions. What do you think?

**Comment by Luni-4** [comment]
> I think that we should revert the part of the commit that involved rust files, in order to keep the integration with the CI without regressions. What do you think?

Can we fix tests without reverting the commit? Because if we revert that, `tree-sitter-core` can't be built on stable anymore.

**Comment by dodomorandi** [comment]
We can try, but detecting which change caused some tests to fail is not straightforward. This is, unfortunately, the downside of having integration tests instead of unit tests :disappointed:

**Comment by Luni-4** [comment]
Yeah, you're right. Let me try to investigate on that first, perhaps I can fix the cursed commit :)

**Comment by Luni-4** [comment]
bb137cd and da91815 fix this issue
